In [1]:
import pandas as pd

### Loading the Training Dataset

In [2]:

df_train = pd.read_csv('/content/UNSW_NB15_testing-set.csv')
print("Training Dataset loaded successfully.")

Training Dataset loaded successfully.

Let's take a look at the first few rows of the training dataset.

In [3]:
display(df_train.head())

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.121478,tcp,-,FIN,6,4,258,172,74.087490,...,1,1,0,0,0,1,1,0,Normal,0
1,2,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,...,1,2,0,0,0,1,6,0,Normal,0
2,3,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,...,1,3,0,0,0,2,6,0,Normal,0
3,4,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,...,1,3,1,1,0,2,1,0,Normal,0
4,5,0.449454,tcp,-,FIN,10,6,534,268,33.373826,...,1,40,0,0,0,2,39,0,Normal,0

Now, let's check the information about the training dataset, including data types and non-null counts.

In [4]:
display(df_train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 45 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 175341 non-null  int64
 1   dur                175341 non-null  float64
 2   proto              175341 non-null  object
 3   service            175341 non-null  object
 4   state              175341 non-null  object
 5   spkts              175341 non-null  int64
 6   dpkts              175341 non-null  int64
 7   sbytes             175341 non-null  int64
 8   dbytes             175341 non-null  int64
 9   rate               175341 non-null  float64
 10  sttl               175341 non-null  int64
 11  dttl               175341 non-null  int64
 12  sload              175341 non-null  float64
 13  dload              175341 non-null  float64
 14  sloss              175341 non-null  int64
 15  dloss              175341 non-null  int64
 16  sinpkt             175341 non-null  float64
 17  dinpkt             175341 non-null  float64
 18  sjit               175341 non-null  float64
 19  djit               175341 non-null  float64
 20  swin               175341 non-null  int64
 21  stcpb              175341 non-null  int64
 22  dtcpb              175341 non-null  int64
 23  dwin               175341 non-null  int64
 24  tcprtt             175341 non-null  float64
 25  synack             175341 non-null  float64
 26  ackdat             175341 non-null  float64
 27  smean              175341 non-null  int64
 28  dmean              175341 non-null  int64
 29  trans_depth        175341 non-null  int64
 30  response_body_len  175341 non-null  int64
 31  ct_srv_src         175341 non-null  int64
 32  ct_state_ttl       175341 non-null  int64
 33  ct_dst_ltm         175341 non-null  int64
 34  ct_src_dport_ltm   175341 non-null  int64
 35  ct_dst_sport_ltm   175341 non-null  int64
 36  ct_dst_src_ltm     175341 non-null  int64
 37  is_ftp_login       175341 non-null  int64
 38  ct_ftp_cmd         175341 non-null  int64
 39  ct_flw_http_mthd   175341 non-null  int64
 40  ct_src_ltm         175341 non-null  int64
 41  ct_srv_dst         175341 non-null  int64
 42  is_sm_ips_ports    175341 non-null  int64
 43  attack_cat         175341 non-null  object
 44  label              175341 non-null  int64
dtypes: float64(11), int64(30), object(4)
memory usage: 60.2+ MB

None

Let's see the shape (number of rows and columns) of the training dataset.

In [5]:
print(f"Shape of training data: {df_train.shape}")

Shape of training data: (175341, 45)

Let's also get some descriptive statistics for the numerical columns in the training data.

In [6]:
display(df_train.describe())

,id,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
count,175341.000000,175341.000000,175341.000000,175341.000000,1.753410e+05,1.753410e+05,1.753410e+05,175341.000000,175341.000000,1.753410e+05,...,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000
mean,87671.000000,1.359389,20.298664,18.969591,8.844844e+03,1.492892e+04,9.540619e+04,179.546997,79.609567,7.345403e+07,...,5.383538,4.206255,8.729881,0.014948,0.014948,0.133066,6.955789,9.100758,0.015752,0.680622
std,50616.731112,6.480249,136.887597,110.258271,1.747656e+05,1.436542e+05,1.654010e+05,102.940011,110.506863,1.883574e+08,...,8.047104,5.783585,10.956186,0.126048,0.126048,0.701208,8.321493,10.756952,0.124516,0.466237
min,1.000000,0.000000,1.000000,0.000000,2.800000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,43836.000000,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,3.278614e+01,62.000000,0.000000,1.305334e+04,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000
50%,87671.000000,0.001582,2.000000,2.000000,4.300000e+02,1.640000e+02,3.225807e+03,254.000000,29.000000,8.796748e+05,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,4.000000,0.000000,1.000000
75%,131506.000000,0.668069,12.000000,10.000000,1.418000e+03,1.102000e+03,1.250000e+05,254.000000,252.000000,8.888889e+07,...,5.000000,3.000000,12.000000,0.000000,0.000000,0.000000,9.000000,12.000000,0.000000,1.000000
max,175341.000000,59.999989,9616.000000,10974.000000,1.296523e+07,1.465555e+07,1.000000e+06,255.000000,254.000000,5.988000e+09,...,51.000000,46.000000,65.000000,4.000000,4.000000,30.000000,60.000000,62.000000,1.000000,1.000000

### Loading the Testing Dataset

In [7]:
df_test = pd.read_csv('/content/UNSW_NB15_training-set.csv')
print("Testing Dataset loaded successfully.")

Testing Dataset loaded successfully.

Let's take a look at the first few rows of the testing dataset.

In [8]:
display(df_test.head())
df_train=df_train

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

Now, let's check the information about the testing dataset, including data types and non-null counts.

In [9]:
display(df_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82332 entries, 0 to 82331
Data columns (total 45 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 82332 non-null  int64
 1   dur                82332 non-null  float64
 2   proto              82332 non-null  object
 3   service            82332 non-null  object
 4   state              82332 non-null  object
 5   spkts              82332 non-null  int64
 6   dpkts              82332 non-null  int64
 7   sbytes             82332 non-null  int64
 8   dbytes             82332 non-null  int64
 9   rate               82332 non-null  float64
 10  sttl               82332 non-null  int64
 11  dttl               82332 non-null  int64
 12  sload              82332 non-null  float64
 13  dload              82332 non-null  float64
 14  sloss              82332 non-null  int64
 15  dloss              82332 non-null  int64
 16  sinpkt             82332 non-null  float64
 17  dinpkt             82332 non-null  float64
 18  sjit               82332 non-null  float64
 19  djit               82332 non-null  float64
 20  swin               82332 non-null  int64
 21  stcpb              82332 non-null  int64
 22  dtcpb              82332 non-null  int64
 23  dwin               82332 non-null  int64
 24  tcprtt             82332 non-null  float64
 25  synack             82332 non-null  float64
 26  ackdat             82332 non-null  float64
 27  smean              82332 non-null  int64
 28  dmean              82332 non-null  int64
 29  trans_depth        82332 non-null  int64
 30  response_body_len  82332 non-null  int64
 31  ct_srv_src         82332 non-null  int64
 32  ct_state_ttl       82332 non-null  int64
 33  ct_dst_ltm         82332 non-null  int64
 34  ct_src_dport_ltm   82332 non-null  int64
 35  ct_dst_sport_ltm   82332 non-null  int64
 36  ct_dst_src_ltm     82332 non-null  int64
 37  is_ftp_login       82332 non-null  int64
 38  ct_ftp_cmd         82332 non-null  int64
 39  ct_flw_http_mthd   82332 non-null  int64
 40  ct_src_ltm         82332 non-null  int64
 41  ct_srv_dst         82332 non-null  int64
 42  is_sm_ips_ports    82332 non-null  int64
 43  attack_cat         82332 non-null  object
 44  label              82332 non-null  int64
dtypes: float64(11), int64(30), object(4)
memory usage: 28.3+ MB

None

Let's see the shape (number of rows and columns) of the testing dataset.

In [10]:
print(f"Shape of testing data: {df_test.shape}")

Shape of testing data: (82332, 45)

Let's also get some descriptive statistics for the numerical columns in the testing data.

In [11]:
display(df_test.describe())

,id,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
count,82332.000000,82332.000000,82332.000000,82332.000000,8.233200e+04,8.233200e+04,8.233200e+04,82332.000000,82332.000000,8.233200e+04,...,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000
mean,41166.500000,1.006756,18.666472,17.545936,7.993908e+03,1.323379e+04,8.241089e+04,180.967667,95.713003,6.454902e+07,...,4.928898,3.663011,7.456360,0.008284,0.008381,0.129743,6.468360,9.164262,0.011126,0.550600
std,23767.345519,4.710444,133.916353,115.574086,1.716423e+05,1.514715e+05,1.486204e+05,101.513358,116.667722,1.798618e+08,...,8.389545,5.915386,11.415191,0.091171,0.092485,0.638683,8.543927,11.121413,0.104891,0.497436
min,1.000000,0.000000,1.000000,0.000000,2.400000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,20583.750000,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,2.860611e+01,62.000000,0.000000,1.120247e+04,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000
50%,41166.500000,0.014138,6.000000,2.000000,5.340000e+02,1.780000e+02,2.650177e+03,254.000000,29.000000,5.770032e+05,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,5.000000,0.000000,1.000000
75%,61749.250000,0.719360,12.000000,10.000000,1.280000e+03,9.560000e+02,1.111111e+05,254.000000,252.000000,6.514286e+07,...,4.000000,3.000000,6.000000,0.000000,0.000000,0.000000,7.000000,11.000000,0.000000,1.000000
max,82332.000000,59.999989,10646.000000,11018.000000,1.435577e+07,1.465753e+07,1.000000e+06,255.000000,253.000000,5.268000e+09,...,59.000000,38.000000,63.000000,2.000000,2.000000,16.000000,60.000000,62.000000,1.000000,1.000000

### Dropping Irrelevant Columns

I'll drop the `id` column, which is just an identifier, and the `attack_cat` column, as the `label` column already serves as a binary target (0 for normal, 1 for attack) for classification tasks. Keeping both `attack_cat` and `label` might introduce redundancy if the primary goal is binary classification.

In [12]:
columns_to_drop = ['id']

df_train = df_train.drop(columns=columns_to_drop)
df_test = df_test.drop(columns=columns_to_drop)

print(f"Columns dropped from df_train: {columns_to_drop}")
print(f"New shape of df_train: {df_train.shape}")
print(f"\nColumns dropped from df_test: {columns_to_drop}")
print(f"New shape of df_test: {df_test.shape}")

Columns dropped from df_train: ['id']
New shape of df_train: (175341, 44)

Columns dropped from df_test: ['id']
New shape of df_test: (82332, 44)

### Value Counts for the Output Feature ('label')

Now, let's look at the distribution of the 'label' column (our potential output feature) in both the training and testing datasets.

In [13]:
print("Value counts for 'label' in training dataset:")
display(df_train['label'].value_counts())

print("\nValue counts for 'label' in testing dataset:")
display(df_test['label'].value_counts())

Value counts for 'label' in training dataset:

label
1    119341
0     56000
Name: count, dtype: int64

Value counts for 'label' in testing dataset:

label
1    45332
0    37000
Name: count, dtype: int64

### Removing the 'label' (Binary Output) Column

As requested, I will now remove the 'label' column from both datasets. This means we are no longer focusing on the binary classification task.

In [14]:
df_train = df_train.drop(columns=['label'])
df_test = df_test.drop(columns=['label'])

print(f"'label' column dropped from df_train. New shape: {df_train.shape}")
print(f"'label' column dropped from df_test. New shape: {df_test.shape}")

'label' column dropped from df_train. New shape: (175341, 43)
'label' column dropped from df_test. New shape: (82332, 43)

### Value Counts for 'attack_cat'

Now, let's get the value counts for the 'attack_cat' feature in both the training and testing datasets to understand the distribution of different attack types.

In [15]:
print("Value counts for 'attack_cat' in training dataset:")
display(df_train['attack_cat'].value_counts())

print("\nValue counts for 'attack_cat' in testing dataset:")
display(df_test['attack_cat'].value_counts())

Value counts for 'attack_cat' in training dataset:

attack_cat
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130
Name: count, dtype: int64

Value counts for 'attack_cat' in testing dataset:

attack_cat
Normal            37000
Generic           18871
Exploits          11132
Fuzzers            6062
DoS                4089
Reconnaissance     3496
Analysis            677
Backdoor            583
Shellcode           378
Worms                44
Name: count, dtype: int64

In [16]:
df_train.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat'],
      dtype='object')

### Applying SMOTE to Balance the Training Data

To ensure our model is not biased towards the majority classes, we will apply Synthetic Minority Over-sampling Technique (SMOTE) to the training dataset. Since our data contains both numerical and categorical features, we will use `SMOTENC` (SMOTE for Nominal and Continuous features), which handles both types. First, we need to one-hot encode the categorical features.

First, let's identify the categorical and numerical columns, excluding the target `attack_cat`.

In [17]:
from sklearn.model_selection import train_test_split # Ensure import is here or globally available
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, RobustScaler # Ensure import is here or globally available
from sklearn.compose import ColumnTransformer # Ensure import is here or globally available
from imblearn.over_sampling import SMOTENC # Ensure import is here or globally available
import numpy as np

# Separate features (X) and target (y) from the processed df_train
X_train = df_train.drop('attack_cat', axis=1)
y_train = df_train['attack_cat']

# Initialize and fit LabelEncoder here, as it's needed for original and resampled y
label_encoder = LabelEncoder()
label_encoder.fit(y_train) # Fit on the original y_train to capture all classes

# Identify categorical and numerical columns in X_train
categorical_features_X = X_train.select_dtypes(include=['object']).columns
numerical_features_X = X_train.select_dtypes(include=np.number).columns

print(f"Categorical features in X_train: {list(categorical_features_X)}")
print(f"Numerical features in X_train: {list(numerical_features_X)}")

Categorical features in X_train: ['proto', 'service', 'state']
Numerical features in X_train: ['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports']

Now, we will perform one-hot encoding on the identified categorical features in `X_train`. This is a necessary step before applying SMOTENC.

In [18]:
# Apply one-hot encoding to categorical features in X_train
X_train_encoded = pd.get_dummies(X_train, columns=categorical_features_X, drop_first=True)

# Get the indices of the one-hot encoded categorical features for SMOTENC
# SMOTENC needs to know which columns are categorical in the *encoded* dataset
categorical_features_indices = [X_train_encoded.columns.get_loc(col) for col in X_train_encoded.columns if col.startswith(tuple(categorical_features_X))]

print("Shape of X_train after one-hot encoding:", X_train_encoded.shape)
print("Indices of categorical features for SMOTENC:", categorical_features_indices)

Shape of X_train after one-hot encoding: (175341, 191)
Indices of categorical features for SMOTENC: [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190]

Now we can apply SMOTENC to the one-hot encoded training data to balance the classes based on 'attack_cat'.

In [19]:
# Initialize SMOTENC. Note: SMOTENC requires the original categorical feature indices in the encoded dataset.
# We will balance all classes to the count of the majority class, which is 'Normal'.

smotenc = SMOTENC(categorical_features=categorical_features_indices, random_state=42, sampling_strategy='auto')
X_train_resampled, y_train_resampled = smotenc.fit_resample(X_train_encoded, y_train)

print("Shape of X_train after SMOTENC:", X_train_resampled.shape)
print("Shape of y_train after SMOTENC:", y_train_resampled.shape)

Shape of X_train after SMOTENC: (560000, 191)
Shape of y_train after SMOTENC: (560000,)

### Value Counts of 'attack_cat' After SMOTE

Let's check the distribution of the `attack_cat` column after applying SMOTENC to confirm the balancing effect.

In [20]:
print("Value counts for 'attack_cat' in training dataset after SMOTENC:")
display(y_train_resampled.value_counts())

Value counts for 'attack_cat' in training dataset after SMOTENC:

attack_cat
Normal            56000
Backdoor          56000
Analysis          56000
Fuzzers           56000
Shellcode         56000
Reconnaissance    56000
Exploits          56000
DoS               56000
Worms             56000
Generic           56000
Name: count, dtype: int64

In [21]:
# Combine the SMOTENC resampled features and target into a single DataFrame
# X_train_resampled contains one-hot encoded categorical features and numerical features.
# y_train_resampled contains the original string labels (raw attack_cat).
df_train_smoted = pd.concat([X_train_resampled, y_train_resampled.rename('attack_cat')], axis=1)

print(f"Shape of df_train_smoted (after SMOTENC and combining): {df_train_smoted.shape}")

# Now, redefine the development X and y from this SMOTE-balanced data
# The target variable needs to be label encoded using the previously fitted label_encoder
X_development_smoted = df_train_smoted.drop('attack_cat', axis=1)
y_development_smoted_encoded = label_encoder.transform(df_train_smoted['attack_cat'])

print(f"Shape of X_development_smoted: {X_development_smoted.shape}")
print(f"Shape of y_development_smoted_encoded: {y_development_smoted_encoded.shape}")

# Prepare the X_test and y_test_encoded for final evaluation using the same preprocessing steps
X_test_processed = pd.get_dummies(df_test.drop('attack_cat', axis=1), columns=categorical_features_X, drop_first=True)
y_test_encoded = label_encoder.transform(df_test['attack_cat'])

# Align columns of X_test_processed with X_train_encoded (needed for consistent feature set)
missing_cols = set(X_train_encoded.columns) - set(X_test_processed.columns)
for c in missing_cols:
    X_test_processed[c] = 0
X_test_processed = X_test_processed[X_train_encoded.columns]

print(f"Shape of X_test_processed (for final evaluation): {X_test_processed.shape}")
print(f"Shape of y_test_encoded (for final evaluation): {y_test_encoded.shape}")

Shape of df_train_smoted (after SMOTENC and combining): (560000, 192)
Shape of X_development_smoted: (560000, 191)
Shape of y_development_smoted_encoded: (560000,)
Shape of X_test_processed (for final evaluation): (82332, 191)
Shape of y_test_encoded (for final evaluation): (82332,)

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, RobustScaler
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd

# --- Step 1: Define columns to drop ---
cols_to_drop = [
    'sload', 'dload', 'rate', 'sloss', 'dloss',
    'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd',
    'trans_depth', 'response_body_len'
]

# --- Step 2: Drop redundant columns from df_train and df_test directly ---
# Ensure these columns exist before dropping
existing_cols_to_drop_train = [col for col in cols_to_drop if col in df_train.columns]
df_train = df_train.drop(columns=existing_cols_to_drop_train) # Directly modify df_train

print(f"Dropped {existing_cols_to_drop_train} from df_train.")
print(f"Shape of df_train after dropping redundant columns: {df_train.shape}")

# --- Step 2 (continued): Drop redundant columns from df_test ---
# Ensure these columns exist before dropping
existing_cols_to_drop_test = [col for col in cols_to_drop if col in df_test.columns]
df_test = df_test.drop(columns=existing_cols_to_drop_test) # Directly modify df_test

print(f"Dropped {existing_cols_to_drop_test} from df_test.")
print(f"Shape of df_test after dropping redundant columns: {df_test.shape}")

Dropped ['sload', 'dload', 'rate', 'sloss', 'dloss', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'trans_depth', 'response_body_len'] from df_train.
Shape of df_train after dropping redundant columns: (175341, 33)
Dropped ['sload', 'dload', 'rate', 'sloss', 'dloss', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'trans_depth', 'response_body_len'] from df_test.
Shape of df_test after dropping redundant columns: (82332, 33)

In [23]:
# --- Step 4: Perform a train_test_split (80/20) for internal development with stratification ---
# This split is from the SMOTE-balanced data (derived from original df_train) to create internal training and validation sets.
X_train_internal, X_val_internal, y_train_internal, y_val_internal = train_test_split(
    X_development_smoted, y_development_smoted_encoded, test_size=0.2, random_state=42, stratify=y_development_smoted_encoded
)

print(f"X_train_internal shape: {X_train_internal.shape}")
print(f"X_val_internal shape: {X_val_internal.shape}")
print(f"y_train_internal shape: {y_train_internal.shape}")
print(f"y_val_internal shape: {y_val_internal.shape}")

print("\nClass distribution in y_train_internal (after split from SMOTED data):")
unique, counts = np.unique(y_train_internal, return_counts=True)
for label, count in zip(unique, counts):
    print(f"{label_encoder.inverse_transform([label])[0]}: {count}")

print("\nClass distribution in y_val_internal (after split from SMOTED data):")
unique, counts = np.unique(y_val_internal, return_counts=True)
for label, count in zip(unique, counts):
    print(f"{label_encoder.inverse_transform([label])[0]}: {count}")

X_train_internal shape: (448000, 191)
X_val_internal shape: (112000, 191)
y_train_internal shape: (448000,)
y_val_internal shape: (112000,)

Class distribution in y_train_internal (after split from SMOTED data):
Analysis: 44800
Backdoor: 44800
DoS: 44800
Exploits: 44800
Fuzzers: 44800
Generic: 44800
Normal: 44800
Reconnaissance: 44800
Shellcode: 44800
Worms: 44800

Class distribution in y_val_internal (after split from SMOTED data):
Analysis: 11200
Backdoor: 11200
DoS: 11200
Exploits: 11200
Fuzzers: 11200
Generic: 11200
Normal: 11200
Reconnaissance: 11200
Shellcode: 11200
Worms: 11200

In [24]:
from sklearn.pipeline import Pipeline # Changed from imblearn.pipeline.Pipeline to sklearn.pipeline

# --- Step 5: Separate the remaining features into numerical and categorical lists ---
# Since X_train_internal already has one-hot encoded features (as a result of previous SMOTE preprocessing),
# all features are effectively numerical. No object-type categorical features remain.
numerical_features = X_train_internal.columns.tolist() # All columns are now numerical
categorical_features = [] # Explicitly empty as no object-type features are left for OneHotEncoder

print(f"Numerical features: {numerical_features}")
print(f"Categorical features: {categorical_features}")

# --- Step 6: Use ColumnTransformer for preprocessing (only scaling now) ---
# The ColumnTransformer will only apply RobustScaler to all features.
# OneHotEncoder is no longer needed here as features are already one-hot encoded.
preprocessor = ColumnTransformer(
    transformers=[
        ('num', RobustScaler(), numerical_features)
    ],
    remainder='passthrough' # Keep any other columns if they exist (should not in this setup)
)

# --- Step 7: Create a pipeline with preprocessor and classifier (SMOTENC removed) ---
# SMOTENC is removed from the pipeline because the data (X_development_smoted) is already SMOTE-balanced
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

print("Fitting preprocessor and classifier on internal training data (SMOTENC already applied to data)...")
pipeline.fit(X_train_internal, y_train_internal)
print("Preprocessing and model training on internal training data complete.")

Numerical features: ['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports', 'proto_a/n', 'proto_aes-sp3-d', 'proto_any', 'proto_argus', 'proto_aris', 'proto_arp', 'proto_ax.25', 'proto_bbn-rcc', 'proto_bna', 'proto_br-sat-mon', 'proto_cbt', 'proto_cftp', 'proto_chaos', 'proto_compaq-peer', 'proto_cphb', 'proto_cpnx', 'proto_crtp', 'proto_crudp', 'proto_dcn', 'proto_ddp', 'proto_ddx', 'proto_dgp', 'proto_egp', 'proto_eigrp', 'proto_emcon', 'proto_encap', 'proto_etherip', 'proto_fc', 'proto_fire', 'proto_ggp', 'proto_gmtp', 'proto_gre', 'proto_hmp', 'proto_i-nlsp', 'proto_iatp', 'proto_ib', 'proto_icmp', 'proto_idpr', 'proto_idpr-cmtp', 'proto_idrp', 'proto_ifmp', 'proto_igmp', 'proto_igp', 'proto_il', 'proto_ip', 'proto_ipcomp', 'proto_ipcv', 'proto_ipip', 'proto_iplt', 'proto_ipnip', 'proto_ippc', 'proto_ipv6', 'proto_ipv6-frag', 'proto_ipv6-no', 'proto_ipv6-opts', 'proto_ipv6-route', 'proto_ipx-n-ip', 'proto_irtp', 'proto_isis', 'proto_iso-ip', 'proto_iso-tp4', 'proto_kryptolan', 'proto_l2tp', 'proto_larp', 'proto_leaf-1', 'proto_leaf-2', 'proto_merit-inp', 'proto_mfe-nsp', 'proto_mhrp', 'proto_micp', 'proto_mobile', 'proto_mtp', 'proto_mux', 'proto_narp', 'proto_netblt', 'proto_nsfnet-igp', 'proto_nvp', 'proto_ospf', 'proto_pgm', 'proto_pim', 'proto_pipe', 'proto_pnni', 'proto_pri-enc', 'proto_prm', 'proto_ptp', 'proto_pup', 'proto_pvp', 'proto_qnx', 'proto_rdp', 'proto_rsvp', 'proto_rtp', 'proto_rvd', 'proto_sat-expak', 'proto_sat-mon', 'proto_sccopmce', 'proto_scps', 'proto_sctp', 'proto_sdrp', 'proto_secure-vmtp', 'proto_sep', 'proto_skip', 'proto_sm', 'proto_smp', 'proto_snp', 'proto_sprite-rpc', 'proto_sps', 'proto_srp', 'proto_st2', 'proto_stp', 'proto_sun-nd', 'proto_swipe', 'proto_tcf', 'proto_tcp', 'proto_tlsp', 'proto_tp++', 'proto_trunk-1', 'proto_trunk-2', 'proto_ttp', 'proto_udp', 'proto_unas', 'proto_uti', 'proto_vines', 'proto_visa', 'proto_vmtp', 'proto_vrrp', 'proto_wb-expak', 'proto_wb-mon', 'proto_wsn', 'proto_xnet', 'proto_xns-idp', 'proto_xtp', 'proto_zero', 'service_dhcp', 'service_dns', 'service_ftp', 'service_ftp-data', 'service_http', 'service_irc', 'service_pop3', 'service_radius', 'service_smtp', 'service_snmp', 'service_ssh', 'service_ssl', 'state_ECO', 'state_FIN', 'state_INT', 'state_PAR', 'state_REQ', 'state_RST', 'state_URN', 'state_no']
Categorical features: []
Fitting preprocessor and classifier on internal training data (SMOTENC already applied to data)...
Preprocessing and model training on internal training data complete.

### Step 10: Hyperparameter Tuning with RandomizedSearchCV

To further improve the model's performance and generalization, especially on minority classes, we will perform hyperparameter tuning using `RandomizedSearchCV`. We'll define a search space for key `RandomForestClassifier` parameters.

In [25]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(random_state=42, eval_metric='logloss'))
])

print("Fitting preprocessor and XGBoost classifier on internal training data...")
pipeline_xgb.fit(X_train_internal, y_train_internal)
print("Preprocessing and model training on internal training data complete.")

# --- Step 8: Evaluate on internal validation set ---
y_val_pred_xgb = pipeline_xgb.predict(X_val_internal)

print("\nClassification Report for Internal Validation Set (XGBoost):")
print(classification_report(y_val_internal, y_val_pred_xgb, target_names=label_encoder.classes_))

# --- Step 9: Final evaluation on the separate, unseen test set (df_test) ---
print("\nNow evaluating the XGBoost model on the completely unseen df_test dataset...")
# Note: If X_test_processed is already preprocessed, passing it through the pipeline will preprocess it twice.
# Use your raw X_test here if the pipeline handles preprocessing.
y_test_pred_xgb = pipeline_xgb.predict(X_test_processed)

print("\nClassification Report for Final Test Set (XGBoost):")
print(classification_report(y_test_encoded, y_test_pred_xgb, target_names=label_encoder.classes_))

Fitting preprocessor and XGBoost classifier on internal training data...
Preprocessing and model training on internal training data complete.

Classification Report for Internal Validation Set (XGBoost):
                precision    recall  f1-score   support

      Analysis       0.52      0.53      0.53     11200
      Backdoor       0.45      0.72      0.55     11200
           DoS       0.55      0.50      0.53     11200
      Exploits       0.78      0.52      0.62     11200
       Fuzzers       0.86      0.86      0.86     11200
       Generic       1.00      0.98      0.99     11200
        Normal       0.96      0.88      0.92     11200
Reconnaissance       0.95      0.79      0.86     11200
     Shellcode       0.94      0.98      0.96     11200
         Worms       0.99      1.00      0.99     11200

      accuracy                           0.78    112000
     macro avg       0.80      0.78      0.78    112000
  weighted avg       0.80      0.78      0.78    112000


Now evaluating the XGBoost model on the completely unseen df_test dataset...

Classification Report for Final Test Set (XGBoost):
                precision    recall  f1-score   support

      Analysis       0.04      0.22      0.07       677
      Backdoor       0.03      0.16      0.05       583
           DoS       0.33      0.39      0.36      4089
      Exploits       0.80      0.60      0.69     11132
       Fuzzers       0.27      0.60      0.38      6062
       Generic       1.00      0.97      0.98     18871
        Normal       0.97      0.68      0.80     37000
Reconnaissance       0.86      0.82      0.84      3496
     Shellcode       0.19      0.91      0.31       378
         Worms       0.17      0.75      0.28        44

      accuracy                           0.71     82332
     macro avg       0.47      0.61      0.48     82332
  weighted avg       0.85      0.71      0.76     82332

In [26]:
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

pipeline_lgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LGBMClassifier(random_state=42, verbose=-1))
])

print("Fitting preprocessor and LightGBM classifier on internal training data...")
pipeline_lgb.fit(X_train_internal, y_train_internal)
print("Preprocessing and model training on internal training data complete.")

# --- Step 8: Evaluate on internal validation set ---
y_val_pred_lgb = pipeline_lgb.predict(X_val_internal)

print("\nClassification Report for Internal Validation Set (LightGBM):")
print(classification_report(y_val_internal, y_val_pred_lgb, target_names=label_encoder.classes_))

# --- Step 9: Final evaluation on the separate, unseen test set (df_test) ---
print("\nNow evaluating the LightGBM model on the completely unseen df_test dataset...")
y_test_pred_lgb = pipeline_lgb.predict(X_test_processed)

print("\nClassification Report for Final Test Set (LightGBM):")
print(classification_report(y_test_encoded, y_test_pred_lgb, target_names=label_encoder.classes_))

Fitting preprocessor and LightGBM classifier on internal training data...
Preprocessing and model training on internal training data complete.

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Classification Report for Internal Validation Set (LightGBM):
                precision    recall  f1-score   support

      Analysis       0.53      0.56      0.54     11200
      Backdoor       0.46      0.72      0.56     11200
           DoS       0.58      0.54      0.56     11200
      Exploits       0.80      0.51      0.62     11200
       Fuzzers       0.86      0.86      0.86     11200
       Generic       1.00      0.98      0.99     11200
        Normal       0.96      0.87      0.92     11200
Reconnaissance       0.95      0.79      0.86     11200
     Shellcode       0.94      0.98      0.96     11200
         Worms       0.99      1.00      0.99     11200

      accuracy                           0.78    112000
     macro avg       0.81      0.78      0.79    112000
  weighted avg       0.81      0.78      0.79    112000


Now evaluating the LightGBM model on the completely unseen df_test dataset...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Classification Report for Final Test Set (LightGBM):
                precision    recall  f1-score   support

      Analysis       0.03      0.15      0.05       677
      Backdoor       0.04      0.22      0.07       583
           DoS       0.33      0.41      0.37      4089
      Exploits       0.80      0.61      0.69     11132
       Fuzzers       0.28      0.62      0.39      6062
       Generic       1.00      0.97      0.98     18871
        Normal       0.98      0.67      0.80     37000
Reconnaissance       0.87      0.82      0.84      3496
     Shellcode       0.18      0.91      0.31       378
         Worms       0.18      0.80      0.29        44

      accuracy                           0.71     82332
     macro avg       0.47      0.62      0.48     82332
  weighted avg       0.85      0.71      0.76     82332

In [27]:
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

# Using a standard architecture (e.g., two hidden layers of 100 and 50 neurons)
# max_iter is increased to 1000 to ensure the network converges
pipeline_nn = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42))
])

print("Fitting preprocessor and Neural Network on internal training data...")
pipeline_nn.fit(X_train_internal, y_train_internal)
print("Preprocessing and model training on internal training data complete.")

# --- Step 8: Evaluate on internal validation set ---
y_val_pred_nn = pipeline_nn.predict(X_val_internal)

print("\nClassification Report for Internal Validation Set (Neural Network):")
print(classification_report(y_val_internal, y_val_pred_nn, target_names=label_encoder.classes_))

# --- Step 9: Final evaluation on the separate, unseen test set (df_test) ---
print("\nNow evaluating the Neural Network on the completely unseen df_test dataset...")
y_test_pred_nn = pipeline_nn.predict(X_test_processed)

print("\nClassification Report for Final Test Set (Neural Network):")
print(classification_report(y_test_encoded, y_test_pred_nn, target_names=label_encoder.classes_))

Fitting preprocessor and Neural Network on internal training data...
Preprocessing and model training on internal training data complete.

Classification Report for Internal Validation Set (Neural Network):
                precision    recall  f1-score   support

      Analysis       0.54      0.61      0.57     11200
      Backdoor       0.51      0.62      0.56     11200
           DoS       0.50      0.60      0.55     11200
      Exploits       0.76      0.51      0.61     11200
       Fuzzers       0.84      0.85      0.84     11200
       Generic       1.00      0.98      0.99     11200
        Normal       0.95      0.86      0.90     11200
Reconnaissance       0.92      0.79      0.85     11200
     Shellcode       0.94      0.95      0.94     11200
         Worms       0.95      0.99      0.97     11200

      accuracy                           0.77    112000
     macro avg       0.79      0.77      0.78    112000
  weighted avg       0.79      0.77      0.78    112000


Now evaluating the Neural Network on the completely unseen df_test dataset...

Classification Report for Final Test Set (Neural Network):
                precision    recall  f1-score   support

      Analysis       0.01      0.07      0.02       677
      Backdoor       0.04      0.25      0.07       583
           DoS       0.33      0.26      0.29      4089
      Exploits       0.72      0.62      0.67     11132
       Fuzzers       0.24      0.52      0.33      6062
       Generic       1.00      0.89      0.94     18871
        Normal       0.96      0.65      0.78     37000
Reconnaissance       0.75      0.83      0.78      3496
     Shellcode       0.19      0.79      0.30       378
         Worms       0.01      0.39      0.02        44

      accuracy                           0.67     82332
     macro avg       0.42      0.53      0.42     82332
  weighted avg       0.82      0.67      0.73     82332

In [30]:
!pip install scikeras

Collecting scikit-learn<1.6.0
  Downloading scikit_learn-1.5.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<1.6.0) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<1.6.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<1.6.0) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<1.6.0) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn<1.6.0) (3.1.2)
Downloading scikit_learn-1.5.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 25.6 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.44 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed scikit-learn-1.5.2

In [31]:
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
import numpy as np
from sklearn.metrics import classification_report

# 1. Transform data manually using your preprocessor
X_train_trans = preprocessor.fit_transform(X_train_internal)
X_val_trans = preprocessor.transform(X_val_internal)
# Assuming X_test_processed is the raw test data before preprocessing:
X_test_trans = preprocessor.transform(X_test_processed)

# Convert sparse matrices to dense arrays (required for Keras)
if hasattr(X_train_trans, "toarray"):
    X_train_trans = X_train_trans.toarray()
    X_val_trans = X_val_trans.toarray()
    X_test_trans = X_test_trans.toarray()

# 2. Define the Deep Neural Network exactly as before
def build_model(n_features, n_classes):
    inputs = layers.Input(shape=(n_features,))
    x = layers.Dense(256, kernel_initializer='he_normal')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(128, kernel_initializer='he_normal')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(64, kernel_initializer='he_normal')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Dropout(0.2)(x)

    if n_classes == 2:
        outputs = layers.Dense(1, activation='sigmoid')(x)
        loss = 'binary_crossentropy'
    else:
        outputs = layers.Dense(n_classes, activation='softmax')(x)
        loss = 'sparse_categorical_crossentropy'

    model = models.Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer=tf.keras.optimizers.AdamW(learning_rate=1e-3, weight_decay=1e-4),
                  loss=loss, metrics=['accuracy'])
    return model

n_classes = len(label_encoder.classes_)
model = build_model(X_train_trans.shape[1], n_classes)

# 3. Train the model natively
print("Training Native Keras Deep NN...")
early_stopping = callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

model.fit(
    X_train_trans, y_train_internal,
    validation_data=(X_val_trans, y_val_internal),
    epochs=100,
    batch_size=64,
    callbacks=[early_stopping],
    verbose=1 # Set to 1 so you can see progress
)

# 4. Custom Prediction Logic (since Keras outputs probabilities)
def predict_classes(keras_model, X):
    preds = keras_model.predict(X, verbose=0)
    if n_classes == 2:
        return (preds > 0.5).astype(int).flatten()
    return np.argmax(preds, axis=1)

# --- Step 8: Evaluate on internal validation set ---
y_val_pred_dnn = predict_classes(model, X_val_trans)
print("\nClassification Report for Internal Validation Set (Deep NN):")
print(classification_report(y_val_internal, y_val_pred_dnn, target_names=label_encoder.classes_))

# --- Step 9: Final evaluation on the separate, unseen test set ---
y_test_pred_dnn = predict_classes(model, X_test_trans)
print("\nClassification Report for Final Test Set (Deep NN):")
print(classification_report(y_test_encoded, y_test_pred_dnn, target_names=label_encoder.classes_))

Training Native Keras Deep NN...
Epoch 1/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 55s 7ms/step - accuracy: 0.3842 - loss: 1.6299 - val_accuracy: 0.3532 - val_loss: 2.0183
Epoch 2/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 75s 6ms/step - accuracy: 0.4695 - loss: 1.4071 - val_accuracy: 0.2701 - val_loss: 2.2305
Epoch 3/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.4958 - loss: 1.3228 - val_accuracy: 0.3056 - val_loss: 2.2098
Epoch 4/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 45s 6ms/step - accuracy: 0.5068 - loss: 1.2845 - val_accuracy: 0.2541 - val_loss: 2.1272
Epoch 5/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.5180 - loss: 1.2467 - val_accuracy: 0.3482 - val_loss: 1.8755
Epoch 6/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.5250 - loss: 1.2264 - val_accuracy: 0.2352 - val_loss: 2.5495
Epoch 7/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 45s 6ms/step - accuracy: 0.5309 - loss: 1.2037 - val_accuracy: 0.3017 - val_loss: 2.1268
Epoch 8/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 84s 7ms/step - accuracy: 0.5371 - loss: 1.1834 - val_accuracy: 0.2670 - val_loss: 1.9801
Epoch 9/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.5407 - loss: 1.1735 - val_accuracy: 0.3125 - val_loss: 2.0713
Epoch 10/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 45s 6ms/step - accuracy: 0.5486 - loss: 1.1491 - val_accuracy: 0.3337 - val_loss: 1.8163
Epoch 11/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 50s 7ms/step - accuracy: 0.5509 - loss: 1.1424 - val_accuracy: 0.3055 - val_loss: 1.9931
Epoch 12/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 77s 6ms/step - accuracy: 0.5569 - loss: 1.1249 - val_accuracy: 0.4147 - val_loss: 1.5664
Epoch 13/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 43s 6ms/step - accuracy: 0.5570 - loss: 1.1250 - val_accuracy: 0.2943 - val_loss: 1.9697
Epoch 14/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 44s 6ms/step - accuracy: 0.5633 - loss: 1.1089 - val_accuracy: 0.3706 - val_loss: 1.8140
Epoch 15/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.5650 - loss: 1.1049 - val_accuracy: 0.3848 - val_loss: 1.8636
Epoch 16/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 45s 6ms/step - accuracy: 0.5731 - loss: 1.0846 - val_accuracy: 0.2157 - val_loss: 2.3476
Epoch 17/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.5748 - loss: 1.0788 - val_accuracy: 0.2489 - val_loss: 2.2830
Epoch 18/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 45s 6ms/step - accuracy: 0.5762 - loss: 1.0753 - val_accuracy: 0.3125 - val_loss: 2.0716
Epoch 19/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 45s 6ms/step - accuracy: 0.5788 - loss: 1.0643 - val_accuracy: 0.3903 - val_loss: 1.6545
Epoch 20/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 44s 6ms/step - accuracy: 0.5823 - loss: 1.0591 - val_accuracy: 0.3456 - val_loss: 1.8490
Epoch 21/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 44s 6ms/step - accuracy: 0.5835 - loss: 1.0554 - val_accuracy: 0.3091 - val_loss: 1.8581
Epoch 22/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.5885 - loss: 1.0450 - val_accuracy: 0.4204 - val_loss: 1.4972
Epoch 23/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 45s 6ms/step - accuracy: 0.5930 - loss: 1.0332 - val_accuracy: 0.4412 - val_loss: 1.5023
Epoch 24/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.5963 - loss: 1.0248 - val_accuracy: 0.2766 - val_loss: 2.3841
Epoch 25/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.5967 - loss: 1.0261 - val_accuracy: 0.4106 - val_loss: 1.7270
Epoch 26/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 81s 7ms/step - accuracy: 0.5982 - loss: 1.0230 - val_accuracy: 0.5152 - val_loss: 1.2662
Epoch 27/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 47s 7ms/step - accuracy: 0.6019 - loss: 1.0146 - val_accuracy: 0.5636 - val_loss: 1.2416
Epoch 28/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6036 - loss: 1.0108 - val_accuracy: 0.2991 - val_loss: 2.3248
Epoch 29/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 49s 7ms/step - accuracy: 0.6057 - loss: 1.0083 - val_accuracy: 0.2939 - val_loss: 1.9931
Epoch 30/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 80s 7ms/step - accuracy: 0.6056 - loss: 1.0075 - val_accuracy: 0.4921 - val_loss: 1.3105
Epoch 31/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 49s 7ms/step - accuracy: 0.6085 - loss: 1.0009 - val_accuracy: 0.2909 - val_loss: 1.9380
Epoch 32/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6080 - loss: 1.0025 - val_accuracy: 0.2886 - val_loss: 1.9337
Epoch 33/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6136 - loss: 0.9925 - val_accuracy: 0.5045 - val_loss: 1.3087
Epoch 34/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6133 - loss: 0.9917 - val_accuracy: 0.5589 - val_loss: 1.0988
Epoch 35/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 47s 7ms/step - accuracy: 0.6172 - loss: 0.9816 - val_accuracy: 0.3807 - val_loss: 1.6933
Epoch 36/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6195 - loss: 0.9761 - val_accuracy: 0.5559 - val_loss: 1.2013
Epoch 37/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 80s 6ms/step - accuracy: 0.6175 - loss: 0.9806 - val_accuracy: 0.3076 - val_loss: 2.0340
Epoch 38/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 47s 7ms/step - accuracy: 0.6184 - loss: 0.9767 - val_accuracy: 0.2810 - val_loss: 2.1402
Epoch 39/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.6201 - loss: 0.9728 - val_accuracy: 0.5232 - val_loss: 1.2807
Epoch 40/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6237 - loss: 0.9668 - val_accuracy: 0.4244 - val_loss: 1.4861
Epoch 41/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 47s 7ms/step - accuracy: 0.6253 - loss: 0.9624 - val_accuracy: 0.3746 - val_loss: 1.5666
Epoch 42/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6252 - loss: 0.9630 - val_accuracy: 0.3993 - val_loss: 1.7165
Epoch 43/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 48s 7ms/step - accuracy: 0.6275 - loss: 0.9596 - val_accuracy: 0.4731 - val_loss: 1.4075
Epoch 44/100
7000/7000 ━━━━━━━━━━━━━━━━━━━━ 46s 7ms/step - accuracy: 0.6310 - loss: 0.9524 - val_accuracy: 0.4201 - val_loss: 1.5110

Classification Report for Internal Validation Set (Deep NN):
                precision    recall  f1-score   support

      Analysis       0.46      0.53      0.49     11200
      Backdoor       0.27      0.57      0.36     11200
           DoS       0.47      0.05      0.10     11200
      Exploits       0.71      0.41      0.52     11200
       Fuzzers       0.44      0.86      0.58     11200
       Generic       1.00      0.96      0.98     11200
        Normal       1.00      0.78      0.87     11200
Reconnaissance       0.34      0.12      0.17     11200
     Shellcode       0.51      0.61      0.55     11200
         Worms       0.89      0.71      0.79     11200

      accuracy                           0.56    112000
     macro avg       0.61      0.56      0.54    112000
  weighted avg       0.61      0.56      0.54    112000


Classification Report for Final Test Set (Deep NN):
                precision    recall  f1-score   support

      Analysis       0.06      0.44      0.11       677
      Backdoor       0.03      0.24      0.05       583
           DoS       0.26      0.07      0.11      4089
      Exploits       0.84      0.45      0.59     11132
       Fuzzers       0.16      0.76      0.27      6062
       Generic       1.00      0.61      0.76     18871
        Normal       1.00      0.53      0.69     37000
Reconnaissance       0.26      0.11      0.16      3496
     Shellcode       0.07      0.55      0.13       378
         Worms       0.02      0.66      0.05        44

      accuracy                           0.51     82332
     macro avg       0.37      0.44      0.29     82332
  weighted avg       0.83      0.51      0.60     82332

In [ ]:
import numpy as np
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.metrics import classification_report

# 1. Preprocess splits through your transformer pipeline
X_train_trans = preprocessor.fit_transform(X_train_internal)
X_val_trans = preprocessor.transform(X_val_internal)

# Convert sparse matrices to dense arrays if one-hot encoding was used
if hasattr(X_train_trans, "toarray"):
    X_train_trans = X_train_trans.toarray()
    X_val_trans = X_val_trans.toarray()

# Ensure inputs are float32
X_train_trans = np.asarray(X_train_trans, dtype=np.float32)
X_val_trans = np.asarray(X_val_trans, dtype=np.float32)
y_train_arr = np.asarray(y_train_internal)
y_val_arr = np.asarray(y_val_internal)

# 2. Configure TabNet
tabnet_clf = TabNetClassifier(
    n_d=64,                # Width of prediction layer
    n_a=64,                # Width of attention layer
    n_steps=5,             # Number of successive decision steps
    gamma=1.5,             # Feature reuse penalty coefficient
    lambda_sparse=1e-4,    # Sparsity regularizer
    optimizer_params=dict(lr=2e-2),
    scheduler_params={"step_size": 10, "gamma": 0.9},
    scheduler_fn=torch.optim.lr_scheduler.StepLR,
    mask_type='entmax',
    seed=42,
    verbose=10
)

# 3. Fit with internal validation for automatic early stopping
print("Fitting TabNet on internal training data...")
tabnet_clf.fit(
    X_train=X_train_trans,
    y_train=y_train_arr,
    eval_set=[(X_train_trans, y_train_arr), (X_val_trans, y_val_arr)],
    eval_name=['train', 'val'],
    eval_metric=['accuracy'],
    max_epochs=150,
    patience=15,
    batch_size=1024,
    virtual_batch_size=128
)

# --- Step 8: Evaluate on internal validation set ---
y_val_pred_tabnet = tabnet_clf.predict(X_val_trans)
print("\nClassification Report for Internal Validation Set (TabNet):")
print(classification_report(y_val_internal, y_val_pred_tabnet, target_names=label_encoder.classes_))

# --- Step 9: Final evaluation on unseen test set ---
# Ensure X_test_processed is a dense float32 array
if hasattr(X_test_processed, "toarray"):
    X_test_processed = X_test_processed.toarray()
X_test_processed = np.asarray(X_test_processed, dtype=np.float32)

y_test_pred_tabnet = tabnet_clf.predict(X_test_processed)
print("\nClassification Report for Final Test Set (TabNet):")
print(classification_report(y_test_encoded, y_test_pred_tabnet, target_names=label_encoder.classes_))